# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-01 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('link_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysm.Category')),
            ],
            options={
                'ordering': ('url',),
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('officeLocation', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('officeLocation',),
            },
        ),
        migrations.CreateModel(
            name='MediaType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.IntegerField(choices=[(1, 'url'), (2, 'video'), (3, 'pic')])),
            ],
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysm.Location')),
            ],
            options={
                'ordering': ('location',),
            },
        ),
        migrations.CreateModel(
            name='ScreenLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysm.Link')),
                ('sl_screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysm.Screen')),
            ],
        ),
        migrations.AddField(
            model_name='link',
            name='link_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysm.MediaType'),
        ),
    ]
