# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-03 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysm', '0002_auto_20160503_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenlink',
            name='display_time',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
