# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 19:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysm', '0003_screenlink_display_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='screenlink',
            options={'ordering': ('sl_screen',)},
        ),
    ]
