# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysm', '0004_auto_20160509_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenlink',
            name='position',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
